version: 0.2

# $ ecrSource, $IMAGE_NAME, and $ECR_URI need to be populated by CodeBuild

phases:
  install:
    commands:
      - python --version
      - pip install --upgrade pip
      - pip install --upgrade stepfunctions
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - echo Current directory `ls -la`
      - echo Building the AWS Step-Function...
      - echo Path `pwd`
      - python state_machine_manager.py
  post_build:
    commands:
      - echo Build completed on `date`
